#!/usr/bin/env sh

case `uname -o` in
'GNU/Linux')
	cc src/ptree.c -o /usr/bin/ptree -lpthread -Ofast
	mkdir -pv /usr/share/ptree
	cp -TRv lang /usr/share/ptree/lang;;
'Android')
	basepath='/data/data/com.termux/files/usr'
	cc src/ptree.c -o $basepath/bin/ptree -lpthread -Ofast
	mkdir -pv $basepath/share/ptree
	cp -TRv lang $basepath/share/ptree/lang;;
*)
	echo "Operating system `uname -o` is not supported"
	exit 1
esac

