#!/bin/bash

./root-do "
	rm -rf /usr/bin/ptree /usr/lib/ptree
"

if [[ $? == 0 ]]
then
	case "$LANG" in
		es*)
			echo "desinstalado exitosamente.";;
		*)
			echo "uninstalled successfully.";;
	esac
fi




